[build]
rustflags = [
    "--cfg",
    "info_db_fmt=\"rkyv\"",
    "--cfg",
    "tracing_unstable",
]

[env]
# You can set this (during compile time) to change the name of the runtime library
# in the extern prelude of the compiled program.
